### PR TITLE
upgrade go to 1.13 for go mod

### PR DESCRIPTION
**Pull request by movie0125**
build with go 1.13 
failed log
go: golang.org/x/sys@v0.0.0-20190730174312-6a60838ec25: invalid pseudo-version: revision is shorter than canonical (6a60838ec259)

I passed the test in go 1.11 and go 1.13.

### CODE REVIEW

**Comment by movie0125** [comment]
@silenceshell  please help me 

https://dev.azure.com/hubottle/ieevee/_build/results?buildId=5&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=15

build faild with 
image

**Comment by silenceshell** [comment]
Would you try to use the latest version of `x/sys` ? I have tested it works.

```
golang.org/x/sys v0.0.0-20210809222454-d867a43fc93e
```

You could check versions from here:
https://pkg.go.dev/golang.org/x/sys?tab=versions

**Comment by movie0125** [comment]
@silenceshell 
I'm not trying to upgrade the `x/sys` version, it's just that the commit id 6a60838ec25 works fine in GO.11, but not in GO1.13, prompting that the number 9 was added at the end, 6a60838ec259

**Comment by movie0125** [comment]
@silenceshell 
My problem now is that the compilation of CI with Azure Pipelines fails
The following error message is displayed：
https://dev.azure.com/hubottle/d478ffeb-ef80-4615-8ed8-dfe9efc151d0/_apis/build/builds/5/logs/7 

2021-08-06T14:27:48.3437952Z ##[section]Starting: Get dependencies, then build
2021-08-06T14:27:48.3442830Z ==============================================================================
2021-08-06T14:27:48.3443154Z Task         : Command line
2021-08-06T14:27:48.3443446Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2021-08-06T14:27:48.3443730Z Version      : 2.182.0
2021-08-06T14:27:48.3443955Z Author       : Microsoft Corporation
2021-08-06T14:27:48.3444257Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2021-08-06T14:27:48.3444609Z ==============================================================================
2021-08-06T14:27:48.9002365Z Generating script.
2021-08-06T14:27:48.9004041Z ========================== Starting Command Output ===========================
2021-08-06T14:27:48.9010495Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/02dd0ecb-4dd1-4984-949a-5d3416e7763f.sh
2021-08-06T14:27:49.1063887Z go: cannot find GOROOT directory: /usr/local/go1.11
2021-08-06T14:27:49.1064387Z go: cannot find GOROOT directory: /usr/local/go1.11
2021-08-06T14:27:49.1064785Z go: cannot find GOROOT directory: /usr/local/go1.11
2021-08-06T14:27:49.1119130Z ##[error]Bash exited with code '2'.
2021-08-06T14:27:49.1131108Z ##[section]Finishing: Get dependencies, then build

**Comment by silenceshell** [comment]
I have deleted the azure CI pipeline, please try again, thanks.

**Comment by silenceshell** [comment]
> @silenceshell
> I'm not trying to upgrade the `x/sys` version, it's just that the commit id 6a60838ec25 works fine in GO.11, but not in GO1.13, prompting that the number 9 was added at the end, 6a60838ec259

I would like to use the newer golang version, like 1.16, to avoid some odd errors when building.

**Pull request closed without merging**
